from pyqtgraph import PlotWidget
from qtpy import QtCore, QtWidgets


class Ui_MainWindow:
    def setupUi(self, window):
        window.setObjectName("MainWindow")
        window.resize(1101, 737)
        window.centralwidget = QtWidgets.QWidget(window)
        window.centralwidget.setObjectName("centralwidget")
        window.gridLayout_4 = QtWidgets.QGridLayout(window.centralwidget)
        window.gridLayout_4.setObjectName("gridLayout_4")
        window.gridLayout = QtWidgets.QGridLayout()
        window.gridLayout.setObjectName("gridLayout")
        window.plotItem_header_v = PlotWidget(window.centralwidget)
        window.plotItem_header_v.setMaximumSize(QtCore.QSize(90, 16777215))
        window.plotItem_header_v.setObjectName("plotItem_header_v")
        window.gridLayout.addWidget(window.plotItem_header_v, 3, 5, 1, 1)
        window.plotItem_header_h = PlotWidget(window.centralwidget)
        window.plotItem_header_h.setMaximumSize(QtCore.QSize(16777215, 90))
        window.plotItem_header_h.setObjectName("plotItem_header_h")
        window.gridLayout.addWidget(window.plotItem_header_h, 1, 3, 1, 1)
        spacer_item = QtWidgets.QSpacerItem(
            13, 17, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum
        )
        window.gridLayout.addItem(spacer_item, 4, 6, 1, 1)
        window.plotItem_seismic = PlotWidget(window.centralwidget)
        window.plotItem_seismic.setObjectName("plotItem_seismic")
        window.gridLayout.addWidget(window.plotItem_seismic, 3, 3, 1, 1)
        spacer_item_1 = QtWidgets.QSpacerItem(
            13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        window.gridLayout.addItem(spacer_item_1, 2, 0, 2, 1)
        window.frame_header_h = QtWidgets.QFrame(window.centralwidget)
        window.frame_header_h.setFrameShape(QtWidgets.QFrame.StyledPanel)
        window.frame_header_h.setFrameShadow(QtWidgets.QFrame.Raised)
        window.frame_header_h.setObjectName("frame_header_h")
        window.gridLayout_3 = QtWidgets.QGridLayout(window.frame_header_h)
        window.gridLayout_3.setObjectName("gridLayout_3")
        window.comboBox_header = QtWidgets.QComboBox(window.frame_header_h)
        window.comboBox_header.setMaximumSize(QtCore.QSize(80, 16777215))
        window.comboBox_header.setObjectName("comboBox_header")
        window.gridLayout_3.addWidget(window.comboBox_header, 0, 0, 1, 1)
        window.gridLayout.addWidget(window.frame_header_h, 1, 5, 1, 1)
        spacer_item_2 = QtWidgets.QSpacerItem(
            20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        window.gridLayout.addItem(spacer_item_2, 0, 3, 1, 1)
        window.horizontalScrollBar = QtWidgets.QScrollBar(window.centralwidget)
        window.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        window.horizontalScrollBar.setObjectName("horizontalScrollBar")
        window.gridLayout.addWidget(window.horizontalScrollBar, 4, 3, 1, 1)
        window.frame_seismic = QtWidgets.QFrame(window.centralwidget)
        window.frame_seismic.setMinimumSize(QtCore.QSize(130, 0))
        window.frame_seismic.setMaximumSize(QtCore.QSize(160, 16777215))
        window.frame_seismic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        window.frame_seismic.setFrameShadow(QtWidgets.QFrame.Raised)
        window.frame_seismic.setObjectName("frame_seismic")
        window.vboxLayout_seismic = QtWidgets.QVBoxLayout(window.frame_seismic)
        window.vboxLayout_seismic.setContentsMargins(2, 2, 2, 2)
        window.vboxLayout_seismic.setSpacing(4)
        window.vboxLayout_seismic.setObjectName("vboxLayout_seismic")
        # --- Plot Options groupbox ---
        window.groupBox_options = QtWidgets.QGroupBox(
            "Plot Options", window.frame_seismic
        )
        window.groupBox_options.setObjectName("groupBox_options")
        window.gridLayout_2 = QtWidgets.QGridLayout(window.groupBox_options)
        window.gridLayout_2.setObjectName("gridLayout_2")
        window.gridLayout_2.setContentsMargins(4, 14, 4, 4)
        window.gridLayout_2.setSpacing(2)
        window.label_gain = QtWidgets.QLabel(window.groupBox_options)
        window.label_gain.setObjectName("label_gain")
        window.label_gain.setText("Gain")
        window.gridLayout_2.addWidget(window.label_gain, 1, 0, 1, 1)
        window.lineEdit_gain = QtWidgets.QLineEdit(window.groupBox_options)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(
            window.lineEdit_gain.sizePolicy().hasHeightForWidth()
        )
        window.lineEdit_gain.setSizePolicy(size_policy)
        window.lineEdit_gain.setMaximumSize(QtCore.QSize(65, 16777215))
        window.lineEdit_gain.setObjectName("lineEdit_gain")
        window.gridLayout_2.addWidget(window.lineEdit_gain, 1, 1, 1, 1)
        window.label_sort = QtWidgets.QLabel(window.groupBox_options)
        window.label_sort.setObjectName("label_sort")
        window.label_sort.setText("Chan. Sort")
        window.gridLayout_2.addWidget(window.label_sort, 2, 0, 1, 1)
        window.lineEdit_sort = QtWidgets.QLineEdit(window.groupBox_options)
        window.lineEdit_sort.setMaximumSize(QtCore.QSize(65, 20))
        window.lineEdit_sort.setObjectName("lineEdit_sort")
        window.gridLayout_2.addWidget(window.lineEdit_sort, 2, 1, 1, 1)
        window.widget_display_mode = QtWidgets.QWidget(window.groupBox_options)
        window.widget_display_mode.setObjectName("widget_display_mode")
        window.hbox_display_mode = QtWidgets.QHBoxLayout(window.widget_display_mode)
        window.hbox_display_mode.setContentsMargins(0, 0, 0, 0)
        window.hbox_display_mode.setSpacing(4)
        window.hbox_display_mode.setObjectName("hbox_display_mode")
        window.radio_density = QtWidgets.QRadioButton(
            "Density", window.widget_display_mode
        )
        window.radio_density.setObjectName("radio_density")
        window.radio_wiggle = QtWidgets.QRadioButton(
            "Wiggle", window.widget_display_mode
        )
        window.radio_wiggle.setObjectName("radio_wiggle")
        window.radio_density.setChecked(True)
        window.displayModeGroup = QtWidgets.QButtonGroup(window.groupBox_options)
        window.displayModeGroup.setExclusive(True)
        window.displayModeGroup.addButton(window.radio_density)
        window.displayModeGroup.addButton(window.radio_wiggle)
        window.hbox_display_mode.addWidget(window.radio_density)
        window.hbox_display_mode.addWidget(window.radio_wiggle)
        window.gridLayout_2.addWidget(window.widget_display_mode, 0, 0, 1, 2)
        window.vboxLayout_seismic.addWidget(window.groupBox_options)
        spacer_item_3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        window.vboxLayout_seismic.addItem(spacer_item_3)
        window.label_version = QtWidgets.QLabel(window.frame_seismic)
        window.label_version.setText("viewephys")
        window.label_version.setObjectName("label_version")
        window.vboxLayout_seismic.addWidget(window.label_version)
        # --- Status labels groupbox ---
        window.groupBox_status = QtWidgets.QGroupBox(window.frame_seismic)
        window.groupBox_status.setObjectName("groupBox_status")
        window.gridLayout_status = QtWidgets.QGridLayout(window.groupBox_status)
        window.gridLayout_status.setObjectName("gridLayout_status")
        window.gridLayout_status.setContentsMargins(4, 8, 4, 4)
        window.gridLayout_status.setSpacing(1)
        window.label_txt_t = QtWidgets.QLabel(window.groupBox_status)
        window.label_txt_t.setMaximumSize(QtCore.QSize(20, 20))
        window.label_txt_t.setText("t:")
        window.label_txt_t.setObjectName("label_txt_t")
        window.gridLayout_status.addWidget(window.label_txt_t, 0, 0, 1, 1)
        window.label_t = QtWidgets.QLabel(window.groupBox_status)
        window.label_t.setMinimumSize(QtCore.QSize(70, 0))
        window.label_t.setMaximumSize(QtCore.QSize(80, 20))
        window.label_t.setText("")
        window.label_t.setObjectName("label_t")
        window.gridLayout_status.addWidget(window.label_t, 0, 1, 1, 1)
        window.label_txt_amp = QtWidgets.QLabel(window.groupBox_status)
        window.label_txt_amp.setMaximumSize(QtCore.QSize(20, 20))
        window.label_txt_amp.setText("A:")
        window.label_txt_amp.setObjectName("label_txt_amp")
        window.gridLayout_status.addWidget(window.label_txt_amp, 1, 0, 1, 1)
        window.label_amp = QtWidgets.QLabel(window.groupBox_status)
        window.label_amp.setMinimumSize(QtCore.QSize(70, 0))
        window.label_amp.setMaximumSize(QtCore.QSize(80, 20))
        window.label_amp.setText("")
        window.label_amp.setObjectName("label_amp")
        window.gridLayout_status.addWidget(window.label_amp, 1, 1, 1, 1)
        window.label_txt_h = QtWidgets.QLabel(window.groupBox_status)
        window.label_txt_h.setMaximumSize(QtCore.QSize(20, 20))
        window.label_txt_h.setText("h:")
        window.label_txt_h.setObjectName("label_txt_h")
        window.gridLayout_status.addWidget(window.label_txt_h, 2, 0, 1, 1)
        window.label_h = QtWidgets.QLabel(window.groupBox_status)
        window.label_h.setMinimumSize(QtCore.QSize(70, 0))
        window.label_h.setMaximumSize(QtCore.QSize(80, 20))
        window.label_h.setText("")
        window.label_h.setObjectName("label_h")
        window.gridLayout_status.addWidget(window.label_h, 2, 1, 1, 1)
        window.label_txt_x = QtWidgets.QLabel(window.groupBox_status)
        window.label_txt_x.setMaximumSize(QtCore.QSize(20, 20))
        window.label_txt_x.setText("x:")
        window.label_txt_x.setObjectName("label_txt_x")
        window.gridLayout_status.addWidget(window.label_txt_x, 3, 0, 1, 1)
        window.label_x = QtWidgets.QLabel(window.groupBox_status)
        window.label_x.setMinimumSize(QtCore.QSize(70, 0))
        window.label_x.setMaximumSize(QtCore.QSize(80, 20))
        window.label_x.setText("")
        window.label_x.setObjectName("label_x")
        window.gridLayout_status.addWidget(window.label_x, 3, 1, 1, 1)
        window.vboxLayout_seismic.addWidget(window.groupBox_status)
        window.gridLayout.addWidget(window.frame_seismic, 0, 1, 5, 1)
        window.verticalScrollBar = QtWidgets.QScrollBar(window.centralwidget)
        window.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        window.verticalScrollBar.setObjectName("verticalScrollBar")
        window.gridLayout.addWidget(window.verticalScrollBar, 3, 2, 1, 1)
        window.gridLayout_4.addLayout(window.gridLayout, 0, 0, 1, 1)
        window.setCentralWidget(window.centralwidget)
        window.menubar = QtWidgets.QMenuBar(window)
        window.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 22))
        window.menubar.setObjectName("menubar")
        window.menufile = QtWidgets.QMenu(window.menubar)
        window.menufile.setEnabled(False)
        window.menufile.setObjectName("menufile")
        window.menufile.setTitle("File")
        window.menuView = QtWidgets.QMenu(window.menubar)
        window.menuView.setObjectName("menuView")
        window.menuView.setTitle("View")
        window.menuColormaps = QtWidgets.QMenu(window.menuView)
        window.menuColormaps.setObjectName("menuColormaps")
        window.menuColormaps.setTitle("Colormaps")
        window.setMenuBar(window.menubar)
        window.statusbar = QtWidgets.QStatusBar(window)
        window.statusbar.setObjectName("statusbar")
        window.setStatusBar(window.statusbar)
        window.actionopen = QtWidgets.QAction(window)
        window.actionopen.setEnabled(True)
        window.actionopen.setVisible(True)
        window.actionopen.setText("Open")
        window.actionopen.setObjectName("actionopen")

        window.actionColormap_CET_L2 = QtWidgets.QAction(window)
        window.actionColormap_CET_L2.setText("CET-L2")
        window.actionColormap_CET_L2.setObjectName("actionColormap_CET_L2")

        window.actionColormap_MPL_PuOr = QtWidgets.QAction(window)
        window.actionColormap_MPL_PuOr.setText("PuOr")
        window.actionColormap_MPL_PuOr.setObjectName("actionColormap_MPL_PuOr")

        window.actionColormap_CET_D1 = QtWidgets.QAction(window)
        window.actionColormap_CET_D1.setText("CET-D1")
        window.actionColormap_CET_D1.setObjectName("actionColormap_CET_D1")
        window.actionColormap_CET_D1.setCheckable(True)
        window.actionColormap_CET_D1.setChecked(True)

        window.actionColormap_CET_D6 = QtWidgets.QAction(window)
        window.actionColormap_CET_D6.setText("CET-D6")
        window.actionColormap_CET_D6.setObjectName("actionColormap_CET_D6")
        window.actionColormap_CET_D6.setCheckable(True)

        window.actionColormap_CET_L2.setCheckable(True)
        window.actionColormap_MPL_PuOr.setCheckable(True)

        window.actionAutoDownsample = QtWidgets.QAction(window)
        window.actionAutoDownsample.setCheckable(True)
        window.actionAutoDownsample.setChecked(True)
        window.actionAutoDownsample.setText("Auto Downsample")
        window.actionAutoDownsample.setObjectName("actionAutoDownsample")

        window.menufile.addAction(window.actionopen)
        window.menuColormaps.addAction(window.actionColormap_CET_L2)
        window.menuColormaps.addAction(window.actionColormap_MPL_PuOr)
        window.menuColormaps.addAction(window.actionColormap_CET_D1)
        window.menuColormaps.addAction(window.actionColormap_CET_D6)

        window.menuView.addAction(window.menuColormaps.menuAction())
        window.menuView.addAction(window.actionAutoDownsample)
        window.menubar.addAction(window.menufile.menuAction())
        window.menubar.addAction(window.menuView.menuAction())
        QtCore.QMetaObject.connectSlotsByName(window)
