from pyqtgraph import PlotWidget
from qtpy import QtCore, QtWidgets


class Ui_MainWindow:
    def setupUi(self, window):
        window.setObjectName("MainWindow")
        window.resize(1101, 737)
        window.centralwidget = QtWidgets.QWidget(window)
        window.centralwidget.setObjectName("centralwidget")
        window.gridLayout_4 = QtWidgets.QGridLayout(window.centralwidget)
        window.gridLayout_4.setObjectName("gridLayout_4")
        window.gridLayout = QtWidgets.QGridLayout()
        window.gridLayout.setObjectName("gridLayout")
        window.plotItem_header_v = PlotWidget(window.centralwidget)
        window.plotItem_header_v.setMaximumSize(QtCore.QSize(90, 16777215))
        window.plotItem_header_v.setObjectName("plotItem_header_v")
        window.gridLayout.addWidget(window.plotItem_header_v, 3, 5, 1, 1)
        window.plotItem_header_h = PlotWidget(window.centralwidget)
        window.plotItem_header_h.setMaximumSize(QtCore.QSize(16777215, 90))
        window.plotItem_header_h.setObjectName("plotItem_header_h")
        window.gridLayout.addWidget(window.plotItem_header_h, 1, 3, 1, 1)
        spacer_item = QtWidgets.QSpacerItem(
            13, 17, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum
        )
        window.gridLayout.addItem(spacer_item, 4, 6, 1, 1)
        window.plotItem_seismic = PlotWidget(window.centralwidget)
        window.plotItem_seismic.setObjectName("plotItem_seismic")
        window.gridLayout.addWidget(window.plotItem_seismic, 3, 3, 1, 1)
        spacer_item_1 = QtWidgets.QSpacerItem(
            13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        window.gridLayout.addItem(spacer_item_1, 2, 0, 2, 1)
        window.frame_header_h = QtWidgets.QFrame(window.centralwidget)
        window.frame_header_h.setObjectName("frame_header_h")
        window.gridLayout_3 = QtWidgets.QGridLayout(window.frame_header_h)
        window.gridLayout_3.setObjectName("gridLayout_3")
        window.comboBox_header = QtWidgets.QComboBox(window.frame_header_h)
        window.comboBox_header.setMaximumSize(QtCore.QSize(80, 16777215))
        window.comboBox_header.setObjectName("comboBox_header")
        window.gridLayout_3.addWidget(window.comboBox_header, 0, 0, 1, 1)
        window.gridLayout.addWidget(window.frame_header_h, 1, 1, 1, 1)
        spacer_item_2 = QtWidgets.QSpacerItem(
            20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        window.gridLayout.addItem(spacer_item_2, 0, 3, 1, 1)
        window.horizontalScrollBar = QtWidgets.QScrollBar(window.centralwidget)
        window.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        window.horizontalScrollBar.setObjectName("horizontalScrollBar")
        window.gridLayout.addWidget(window.horizontalScrollBar, 4, 3, 1, 1)
        window.frame_seismic = QtWidgets.QFrame(window.centralwidget)
        window.frame_seismic.setMinimumSize(QtCore.QSize(100, 0))
        window.frame_seismic.setMaximumSize(QtCore.QSize(120, 16777215))
        window.frame_seismic.setObjectName("frame_seismic")
        window.gridLayout_2 = QtWidgets.QGridLayout(window.frame_seismic)
        window.gridLayout_2.setObjectName("gridLayout_2")
        window.label_h = QtWidgets.QLabel(window.frame_seismic)
        window.label_h.setMinimumSize(QtCore.QSize(70, 0))
        window.label_h.setMaximumSize(QtCore.QSize(80, 20))
        window.label_h.setText("")
        window.label_h.setObjectName("label_h")
        window.gridLayout_2.addWidget(window.label_h, 7, 1, 1, 1)
        window.label_txt_h = QtWidgets.QLabel(window.frame_seismic)
        window.label_txt_h.setMaximumSize(QtCore.QSize(10, 20))
        window.label_txt_h.setObjectName("label_txt_h")
        window.gridLayout_2.addWidget(window.label_txt_h, 7, 0, 1, 1)
        window.label_x = QtWidgets.QLabel(window.frame_seismic)
        window.label_x.setMinimumSize(QtCore.QSize(70, 0))
        window.label_x.setMaximumSize(QtCore.QSize(80, 20))
        window.label_x.setText("")
        window.label_x.setObjectName("label_x")
        window.gridLayout_2.addWidget(window.label_x, 7, 1, 1, 1)
        window.lineEdit_sort = QtWidgets.QLineEdit(window.frame_seismic)
        window.lineEdit_sort.setMinimumSize(QtCore.QSize(65, 0))
        window.lineEdit_sort.setMaximumSize(QtCore.QSize(50, 20))
        window.lineEdit_sort.setObjectName("lineEdit_sort")
        window.gridLayout_2.addWidget(window.lineEdit_sort, 2, 1, 1, 1)
        window.label_txt_amp = QtWidgets.QLabel(window.frame_seismic)
        window.label_txt_amp.setMaximumSize(QtCore.QSize(10, 20))
        window.label_txt_amp.setObjectName("label_txt_amp")
        window.gridLayout_2.addWidget(window.label_txt_amp, 6, 0, 1, 1)
        window.label_t = QtWidgets.QLabel(window.frame_seismic)
        window.label_t.setMinimumSize(QtCore.QSize(70, 0))
        window.label_t.setMaximumSize(QtCore.QSize(80, 20))
        window.label_t.setText("")
        window.label_t.setObjectName("label_t")
        window.gridLayout_2.addWidget(window.label_t, 5, 1, 1, 1)
        window.label_gain = QtWidgets.QLabel(window.frame_seismic)
        window.label_gain.setMaximumSize(QtCore.QSize(30, 16777215))
        window.label_gain.setObjectName("label_gain")
        window.gridLayout_2.addWidget(window.label_gain, 0, 0, 1, 1)
        window.lineEdit_gain = QtWidgets.QLineEdit(window.frame_seismic)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(
            window.lineEdit_gain.sizePolicy().hasHeightForWidth()
        )
        window.lineEdit_gain.setSizePolicy(size_policy)
        window.lineEdit_gain.setMinimumSize(QtCore.QSize(65, 0))
        window.lineEdit_gain.setMaximumSize(QtCore.QSize(50, 16777215))
        window.lineEdit_gain.setObjectName("lineEdit_gain")
        window.gridLayout_2.addWidget(window.lineEdit_gain, 0, 1, 1, 1)
        window.label_amp = QtWidgets.QLabel(window.frame_seismic)
        window.label_amp.setMinimumSize(QtCore.QSize(70, 0))
        window.label_amp.setMaximumSize(QtCore.QSize(80, 20))
        window.label_amp.setText("")
        window.label_amp.setObjectName("label_amp")
        window.gridLayout_2.addWidget(window.label_amp, 6, 1, 1, 1)
        window.label_txt_t = QtWidgets.QLabel(window.frame_seismic)
        window.label_txt_t.setMaximumSize(QtCore.QSize(10, 20))
        window.label_txt_t.setObjectName("label_txt_t")
        window.gridLayout_2.addWidget(window.label_txt_t, 5, 0, 1, 1)
        window.label_sort = QtWidgets.QLabel(window.frame_seismic)
        window.label_sort.setMaximumSize(QtCore.QSize(30, 16777215))
        window.label_sort.setObjectName("label_sort")
        window.gridLayout_2.addWidget(window.label_sort, 2, 0, 1, 1)
        window.widget_display_mode = QtWidgets.QWidget(window.frame_seismic)
        window.widget_display_mode.setObjectName("widget_display_mode")
        window.vbox_display_mode = QtWidgets.QVBoxLayout(window.widget_display_mode)
        window.vbox_display_mode.setContentsMargins(0, 0, 0, 0)
        window.vbox_display_mode.setSpacing(2)
        window.vbox_display_mode.setObjectName("vbox_display_mode")
        window.radio_density = QtWidgets.QRadioButton(
            "Density", window.widget_display_mode
        )
        window.radio_density.setObjectName("radio_density")
        window.radio_wiggle = QtWidgets.QRadioButton(
            "Wiggle", window.widget_display_mode
        )
        window.radio_wiggle.setObjectName("radio_wiggle")
        window.checkbox_auto_space_wiggle = QtWidgets.QCheckBox(
            "Auto-space", window.widget_display_mode
        )
        window.checkbox_auto_space_wiggle.setObjectName("checkBox_wiggle_autospace")
        window.checkbox_auto_space_wiggle.setChecked(False)
        window.checkbox_auto_space_wiggle.setEnabled(False)
        window.checkbox_auto_space_wiggle.setStyleSheet(
            "margin-top: 2px; margin-left: 4px;"
        )
        window.radio_density.setToolTip(
            "Density view: render the data as a colour-mapped image, "
            "with amplitude shown as colour intensity."
        )
        window.radio_wiggle.setToolTip("Draw each channel as its own stacked trace. ")
        window.checkbox_auto_space_wiggle.setToolTip(
            "Scale the spacing between wiggle traces by the "
            "widest trace so high-amplitude channels don't overlap their "
            "neighbours. Note gain values are no longer accurate."
        )

        window.radio_density.setChecked(True)
        window.displayModeGroup = QtWidgets.QButtonGroup(window.frame_seismic)
        window.displayModeGroup.setExclusive(True)
        window.displayModeGroup.addButton(window.radio_density)
        window.displayModeGroup.addButton(window.radio_wiggle)
        window.vbox_display_mode.addWidget(window.radio_density)
        window.vbox_display_mode.addWidget(window.radio_wiggle)
        window.vbox_display_mode.addWidget(window.checkbox_auto_space_wiggle)
        window.gridLayout_2.addWidget(window.widget_display_mode, 3, 0, 1, 2)
        spacer_item_3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        window.gridLayout_2.addItem(spacer_item_3, 4, 1, 1, 1)
        window.label_txt_x = QtWidgets.QLabel(window.frame_seismic)
        window.label_txt_x.setMaximumSize(QtCore.QSize(10, 20))
        window.label_txt_x.setObjectName("label_txt_x")
        window.gridLayout_2.addWidget(window.label_txt_x, 5, 0, 1, 1)
        window.label_version = QtWidgets.QLabel(window.frame_seismic)
        window.label_version.setText("viewephys")
        window.gridLayout_2.addWidget(window.label_version, 8, 0, 1, 2)
        window.gridLayout.addWidget(window.frame_seismic, 2, 1, 3, 1)
        window.verticalScrollBar = QtWidgets.QScrollBar(window.centralwidget)
        window.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        window.verticalScrollBar.setObjectName("verticalScrollBar")
        window.gridLayout.addWidget(window.verticalScrollBar, 3, 2, 1, 1)
        window.gridLayout_4.addLayout(window.gridLayout, 0, 0, 1, 1)
        window.setCentralWidget(window.centralwidget)
        window.menubar = QtWidgets.QMenuBar(window)
        window.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 22))
        window.menubar.setObjectName("menubar")
        window.menufile = QtWidgets.QMenu(window.menubar)
        window.menufile.setEnabled(False)
        window.menufile.setObjectName("menufile")
        window.menufile.setTitle("File")
        window.menuView = QtWidgets.QMenu(window.menubar)
        window.menuView.setObjectName("menuView")
        window.menuView.setTitle("View")
        window.menuColormaps = QtWidgets.QMenu(window.menuView)
        window.menuColormaps.setObjectName("menuColormaps")
        window.menuColormaps.setTitle("Colormaps")
        window.setMenuBar(window.menubar)
        window.statusbar = QtWidgets.QStatusBar(window)
        window.statusbar.setObjectName("statusbar")
        window.setStatusBar(window.statusbar)
        window.actionopen = QtWidgets.QAction(window)
        window.actionopen.setEnabled(True)
        window.actionopen.setVisible(True)
        window.actionopen.setText("Open")
        window.actionopen.setObjectName("actionopen")

        window.actionColormap_CET_L2 = QtWidgets.QAction(window)
        window.actionColormap_CET_L2.setText("CET_L2")
        window.actionColormap_CET_L2.setObjectName("actionColormap_CET_L2")

        window.actionColormap_MPL_PuOr = QtWidgets.QAction(window)
        window.actionColormap_MPL_PuOr.setText("MPL_PuOr")
        window.actionColormap_MPL_PuOr.setObjectName("actionColormap_MPL_PuOr")

        window.actionColormap_CET_D1 = QtWidgets.QAction(window)
        window.actionColormap_CET_D1.setText("CET_D1")
        window.actionColormap_CET_D1.setObjectName("actionColormap_CET_D1")

        window.actionColormap_CET_D6 = QtWidgets.QAction(window)
        window.actionColormap_CET_D6.setText("CET_D6")
        window.actionColormap_CET_D6.setObjectName("actionColormap_CET_D6")

        window.menufile.addAction(window.actionopen)
        window.menuColormaps.addAction(window.actionColormap_CET_L2)
        window.menuColormaps.addAction(window.actionColormap_MPL_PuOr)
        window.menuColormaps.addAction(window.actionColormap_CET_D1)
        window.menuColormaps.addAction(window.actionColormap_CET_D6)

        window.menuView.addAction(window.menuColormaps.menuAction())
        window.menubar.addAction(window.menufile.menuAction())
        window.menubar.addAction(window.menuView.menuAction())
        QtCore.QMetaObject.connectSlotsByName(window)
